# Generated by Django 4.2.7 on 2025-12-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_assigned', 'Задача назначена'), ('task_updated', 'Задача обновлена'), ('task_comment', 'Новый комментарий к задаче'), ('document_submitted', 'Документ отправлен на согласование'), ('document_approved', 'Документ согласован'), ('document_rejected', 'Документ отклонен'), ('document_comment', 'Новый комментарий к документу'), ('process_started', 'Процесс запущен'), ('process_completed', 'Процесс завершен'), ('mention', 'Вас упомянули'), ('system', 'Системное уведомление')], max_length=50, verbose_name='Тип')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка')),
                ('related_object_type', models.CharField(blank=True, max_length=50, verbose_name='Тип связанного объекта')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
