# Generated by Django 4.2.7 on 2025-12-06 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('definition', models.JSONField(default=dict, verbose_name='Определение процесса')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('paused', 'Приостановлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_processes', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Процесс',
                'verbose_name_plural': 'Процессы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('current_node', models.CharField(blank=True, max_length=100, verbose_name='Текущий узел')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('paused', 'Приостановлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Статус')),
                ('data', models.JSONField(default=dict, verbose_name='Данные экземпляра')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='processes.process')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_processes', to=settings.AUTH_USER_MODEL, verbose_name='Запустил')),
            ],
            options={
                'verbose_name': 'Экземпляр процесса',
                'verbose_name_plural': 'Экземпляры процессов',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, verbose_name='ID узла')),
                ('node_type', models.CharField(choices=[('start', 'Начало'), ('task', 'Задача'), ('approval', 'Согласование'), ('condition', 'Условие'), ('notification', 'Уведомление'), ('end', 'Конец')], max_length=20, verbose_name='Тип узла')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('position', models.JSONField(default=dict, verbose_name='Позиция')),
                ('config', models.JSONField(default=dict, verbose_name='Конфигурация')),
                ('connections', models.JSONField(default=list, verbose_name='Соединения')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='processes.process')),
            ],
            options={
                'verbose_name': 'Узел процесса',
                'verbose_name_plural': 'Узлы процессов',
                'unique_together': {('process', 'node_id')},
            },
        ),
    ]
